lst=["banana" ,"apple", "orange", "pear", "mango" ]
print("length of list" , len (lst))
print("length of list" , len (lst))
print("last element" , lst[-1])
lst.append("watermelon")
print("updated list" , lst)
lst.remove("pear")
print("updated list" , lst)
lst.append("pear")
print("updated list" , lst)
lst.sort()
print("updated list" , lst)
